---
- name: Permitir que el grupo GProfesores use sudo sin contraseña
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%GProfesores ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

