---
# tasks file for 2PRecuperatorio

- name: "Rol: 2PRecuperatorio"
  debug:
    msg: "Inicio de tareas dentro del Rol: 2PRecuperatorio"

- name: Crear grupo GProfesores
  ansible.builtin.group:
    name: GProfesores
    state: present

- name: Crear grupo GAlumnos
  ansible.builtin.group:
    name: GAlumnos
    state: present

- name: Crear usuario profesor y añadir al grupo GProfesores
  ansible.builtin.user:
    name: profesor
    groups: GProfesores
    state: present

- name: Crear usuario alumno y añadir al grupo GAlumnos
  ansible.builtin.user:
    name: alumno
    groups: GAlumnos
    state: present

- name: "Fin de tareas dentro del Rol: 2PRecuperatorio"
  debug:
    msg: "Tareas completadas en el Rol: 2PRecuperatorio"


